### ISSUE TITLE
istio-csr "failed to generate workload certificate" while regular cert-manager certs generate fine against same issuer

### ISSUE THREAD

**Issue by hyacin75** [cert-manager/istio-csr#149] opened 2022-05-02 04:06 UTC
Done this install successfully on two other clusters this weekend, the third is giving me headaches.

Following several tutorials, cobbled together and then updated as needed ... example - https://medium.com/everything-full-stack/how-to-integrate-vault-as-external-root-ca-with-cert-manager-istio-csr-and-istio-7684baa369db

The other two clusters are happy as anything and all mTLS is using certs from Vault now.

This cluster goes smooth to and through installing istio-csr, but subsequently trying to install istio fails.

The ingressgateway that is failing to deploy says -

```
2022-05-02T03:55:34.117852Z     info    ads     ADS: new connection for node:istio-ingressgateway-internal-7bddbcc6bf-48785.istio-system-3
2022-05-02T03:55:34.300582Z     info    ads     ADS: "@" istio-ingressgateway-internal-7bddbcc6bf-48785.istio-system-2 terminated rpc error: code = Canceled desc = context canceled
2022-05-02T03:55:34.301033Z     warning envoy config    StreamSecrets gRPC config stream closed: 2, failed to generate secret for default: failed to generate workload certificate: create certificate: rpc error: code = Unauthenticated desc = request authenticate failure
2022-05-02T03:55:34.633563Z     warn    sds     failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unauthenticated desc = request authenticate failure
2022-05-02T03:55:34.785551Z     info    ads     ADS: new connection for node:istio-ingressgateway-internal-7bddbcc6bf-48785.istio-system-4
2022-05-02T03:55:34.881997Z     info    ads     ADS: "@" istio-ingressgateway-internal-7bddbcc6bf-48785.istio-system-3 terminated rpc error: code = Canceled desc = context canceled
2022-05-02T03:55:34.882269Z     warning envoy config    StreamSecrets gRPC config stream closed: 2, failed to generate secret for ROOTCA: failed to generate workload certificate: create certificate: rpc error: code = Unauthenticated desc = request authenticate failure
```

and at that point the cert-manager-istio-csr pod is spewing -

```
2022-05-02T03:57:52.201325Z     error   klog    grpc-server "msg"="failed to authenticate request" "error"="could not get cluster hcloud's kube client" "serving-addr"="0.0.0.0:6443"
2022-05-02T03:57:53.874820Z     error   klog    grpc-server "msg"="failed to authenticate request" "error"="could not get cluster hcloud's kube client" "serving-addr"="0.0.0.0:6443"
2022-05-02T03:57:54.879386Z     error   klog    grpc-server "msg"="failed to authenticate request" "error"="could not get cluster hcloud's kube client" "serving-addr"="0.0.0.0:6443"
2022-05-02T03:57:56.600201Z     error   klog    grpc-server "msg"="failed to authenticate request" "error"="could not get cluster hcloud's kube client" "serving-addr"="0.0.0.0:6443"
2022-05-02T03:58:02.333440Z     error   klog    grpc-server "msg"="failed to authenticate request" "error"="could not get cluster hcloud's kube client" "serving-addr"="0.0.0.0:6443"
2022-05-02T03:58:06.919867Z     error   klog    grpc-server "msg"="failed to authenticate request" "error"="could not get cluster hcloud's kube client" "serving-addr"="0.0.0.0:6443"
```

I've spent a full day trying to get this working, searching and trying anything and everything I could find, ripping it all out, and trying again and again with little changes or tweaks or upgrades or whatever I could manage ... I always end up at this same spot.

The biggest differences about this cluster from the other two are, 1) It's ARM64, and 2) it's using docker as a container runtime due to some weird containerd+cni+weave issues happening on ARM with Kubespray right now.

Any help would be GREATLY appreciated.  I'm at a total loss.

I am able to generate a cert against the issuer with a normal certificate request no problem ... it's just istio-csr that is giving me grief.

**Comment by hyacin75** [comment] 2022-05-07 17:19
Now I'm getting the same on a totally different cluster built with microk8s and all amd64 ... very stumped, three clusters no problem, two clusters this problem.  Wish the output from any of the pieces was more descriptive and explained what was going on better.

**Comment by JoshVanL** [comment] 2022-05-07 17:22
Hi @hyacin75, this looks like a duplicate of https://github.com/cert-manager/istio-csr/issues/85#issuecomment-897057232

Can you try setting the cluster name on istio-csr?

**Comment by hyacin75** [comment] 2022-05-09 04:24
Sadly that already is in my filled out template from the tutorial -

`helm --kube-context="hcloud" install -n cert-manager cert-manager-istio-csr jetstack/cert-manager-istio-csr --set app.clusterID=hcloud --set app.certmanager.issuer.name=vault-istio-ca-hcloud-issuer --set app.logLevel=3`

I did rip it out and try again just to be 100% sure, but got the same as above again.

Does it need to match anything other than what is in the subsequent istio operator overrides?

`  values:
    global:
      caAddress: cert-manager-istio-csr.cert-manager.svc:443
      multiCluster:
        clusterName: hcloud
      network: network1
      meshID: mesh1
`

**Closed** 2022-05-09 04:31 UTC
