### ISSUE TITLE
cant install chart v0.5.0

### ISSUE THREAD

**Issue by isality** [cert-manager/istio-csr#178] opened 2022-08-15 11:42 UTC
h1 there

i cant install  v0.5.0. I got error:

```yaml
Error: template: cert-manager-istio-csr/templates/serviceaccount.yaml:3:7: executing "cert-manager-istio-csr/templates/serviceaccount.yaml" at <ne .Values.image.pullSecretName "">: error calling ne: incompatible types for comparison

Use --debug flag to render out invalid YAML
```

I added  `pullSecretName: ""` in `values.yaml`, object  `image` and helm template works fine. Could your check this?

**Comment by JoshVanL** [comment] 2022-08-16 14:38
Hi @isality, this looks to be a duplicate of https://github.com/cert-manager/istio-csr/issues/175
Can you update your helm version, and try again?

**Comment by isality** [comment] 2022-08-17 07:06
H1!

I updated helm to `version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.17.13"}`

And right now i can do `helm template istio-csr ./`

```yaml
---
# Source: cert-manager-istio-csr/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: 
metadata:
  labels:
    app.kubernetes.io/name: cert-manager-istio-csr
    helm.sh/chart: cert-manager-istio-csr-v0.5.0
    app.kubernetes.io/instance: istio-csr
    app.kubernetes.io/version: "v0.5.0"
    app.kubernetes.io/managed-by: Helm
  name: cert-manager-istio-csr

```

But i think it's not okay, when a non-existent field is accessed. See https://github.com/cert-manager/istio-csr/blob/v0.5.0/deploy/charts/istio-csr/templates/serviceaccount.yaml#L3


Thx

**Comment by JoshVanL** [comment] 2022-08-17 07:31
Could you explain this a bit more, I’m not sure I follow?

```
But i think it's not okay, when a non-existent field is accessed
```

**Comment by JoshVanL** [comment] 2022-08-17 07:31
Could you explain this a bit more, I’m not sure I follow?

```
But i think it's not okay, when a non-existent field is accessed
```

**Comment by isality** [comment] 2022-08-17 07:56
Ok, see

Your trying to get value `.Values.image.pullSecretName` [here](https://github.com/cert-manager/istio-csr/blob/v0.5.0/deploy/charts/istio-csr/templates/serviceaccount.yaml#L3), but in [values.yaml](https://github.com/cert-manager/istio-csr/blob/v0.5.0/deploy/charts/istio-csr/values.yaml#L4) your haven't  a field pullSecretName in object image.

**Comment by nitishkrishna** [comment] 2022-08-17 20:06
+1 seeing the same issue, its referring to a non-existing value

**Comment by craigmunro** [comment] 2022-11-08 14:08
Same problem here.  I've raised https://github.com/cert-manager/istio-csr/pull/182 to fix

**Closed** 2022-11-09 12:41 UTC
